### ISSUE TITLE
childHangup is undefined

### ISSUE THREAD

**Issue by ahmadnassri** [tapjs/foreground-child#20]
as mentioned in: https://github.com/tapjs/foreground-child/commit/cdd8a36d881405a63d7afe6c03622f387a1bda63#commitcomment-20210108

- `childHangout` is not defined on [`index.js#L43`](https://github.com/tapjs/foreground-child/blob/master/index.js#L43) 
- and again on [`index.js#L51`](https://github.com/tapjs/foreground-child/blob/master/index.js#L51)

**Comment by JimtotheB** [comment]
Yep, started to open an Issue on tap, its breaking tests run with `--cov` for me.

**Comment by nijikokun** [comment]
:tada:

**Comment by ahmadnassri** [comment]
confirmed fix with [`1.5.6`](https://github.com/tapjs/foreground-child/releases/tag/v1.5.6)
